# Incluído por django-active-static-media.conf quando o app ativo é ENTRADE
location /static/ {
    alias /home/APICLEAR/ENTRADE/staticfiles/;
    expires 30d;
    add_header Cache-Control "public, immutable";
    access_log off;
}

location /media/ {
    alias /home/APICLEAR/ENTRADE/media/;
    expires 30d;
    add_header Cache-Control "public";
}
