# Generated by Django 6.0.4 on 2026-04-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('quote_data', models.JSONField()),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['ticker', '-captured_at'], name='trader_quot_ticker_8395f6_idx')],
            },
        ),
    ]
