# Generated by Django 6.0.4 on 2026-04-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesnapshot',
            name='latency_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotesnapshot',
            name='quote_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
