# Generated by Django 6.0.4 on 2026-04-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_quotesnapshot_latency_ms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16, unique=True)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticker monitorado',
                'verbose_name_plural': 'Tickers monitorados',
                'ordering': ['ticker'],
            },
        ),
    ]

