# Generated by Django 6.0.4 on 2026-04-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_watchedticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('book_data', models.JSONField()),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['ticker', '-captured_at'], name='trader_book_ticker_dd9f72_idx')],
            },
        ),
    ]

