# Generated by Django 4.2.30 on 2026-04-17 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_booksnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnl_type', models.CharField(choices=[('REALIZED', 'Realizado'), ('ESTIMATED', 'Estimado')], db_index=True, max_length=9)),
                ('gross_pnl', models.DecimalField(decimal_places=6, max_digits=18)),
                ('fees', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('net_pnl', models.DecimalField(decimal_places=6, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operação finalizada',
                'verbose_name_plural': 'Operações finalizadas',
                'ordering': ['-closed_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16)),
                ('side', models.CharField(choices=[('LONG', 'Comprado'), ('SHORT', 'Vendido')], db_index=True, max_length=5)),
                ('quantity_open', models.DecimalField(decimal_places=6, max_digits=18)),
                ('avg_open_price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('opened_at', models.DateTimeField(db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Posição',
                'verbose_name_plural': 'Posições',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='PositionLiquidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('FULL', 'Zeragem total'), ('PARTIAL', 'Zeragem parcial')], db_index=True, max_length=8)),
                ('direction', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venda')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('executed_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidations', to='trader.position')),
            ],
            options={
                'verbose_name': 'Liquidação de posição',
                'verbose_name_plural': 'Liquidações de posição',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['ticker', 'is_active'], name='trader_posi_ticker_5da2a8_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['side', 'is_active'], name='trader_posi_side_bfb1cc_idx'),
        ),
        migrations.AddField(
            model_name='closedoperation',
            name='position',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='closed_operation', to='trader.position'),
        ),
        migrations.AddIndex(
            model_name='positionliquidation',
            index=models.Index(fields=['mode', 'executed_at'], name='trader_posi_mode_a009a5_idx'),
        ),
        migrations.AddIndex(
            model_name='positionliquidation',
            index=models.Index(fields=['direction', 'executed_at'], name='trader_posi_directi_db2dc4_idx'),
        ),
        migrations.AddIndex(
            model_name='closedoperation',
            index=models.Index(fields=['pnl_type', 'closed_at'], name='trader_clos_pnl_typ_188691_idx'),
        ),
        migrations.AddIndex(
            model_name='closedoperation',
            index=models.Index(fields=['net_pnl', 'closed_at'], name='trader_clos_net_pnl_f354e8_idx'),
        ),
    ]
