# Generated by Django 4.2.30 on 2026-04-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0005_closedoperation_position_positionliquidation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16)),
                ('side', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venda')], db_index=True, max_length=4)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('marker_at', models.DateTimeField(db_index=True)),
                ('source', models.CharField(blank=True, db_index=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marcação de trade',
                'verbose_name_plural': 'Marcações de trade',
                'ordering': ['-marker_at'],
                'indexes': [models.Index(fields=['ticker', 'marker_at'], name='trader_trad_ticker_b5b665_idx'), models.Index(fields=['side', 'marker_at'], name='trader_trad_side_8e60ef_idx')],
            },
        ),
    ]
