# Generated by Django 4.2.30 on 2026-04-18 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trader', '0007_position_trading_environment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationStrategyToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_key', models.CharField(db_index=True, max_length=64)),
                ('trading_environment', models.CharField(choices=[('simulator', 'Simulador'), ('real', 'Real')], db_index=True, max_length=16)),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_strategy_toggles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estratégia de automação (toggle)',
                'verbose_name_plural': 'Estratégias de automação (toggles)',
                'indexes': [models.Index(fields=['user', 'trading_environment', 'enabled'], name='trader_auto_user_id_2ffb19_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='automationstrategytoggle',
            constraint=models.UniqueConstraint(fields=('user', 'strategy_key', 'trading_environment'), name='trader_automation_strat_user_key_env_uniq'),
        ),
    ]
