# Generated by Django 4.2.30 on 2026-04-18 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trader', '0008_automation_strategy_toggle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationThought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_environment', models.CharField(choices=[('simulator', 'Simulador'), ('real', 'Real')], db_index=True, max_length=16)),
                ('message', models.TextField()),
                ('source', models.CharField(blank=True, db_index=True, max_length=96)),
                ('kind', models.CharField(choices=[('info', 'Info'), ('notice', 'Aviso'), ('warn', 'Alerta'), ('debug', 'Debug')], db_index=True, default='info', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_thoughts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pensamento (log de automação)',
                'verbose_name_plural': 'Pensamentos (logs de automação)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'trading_environment', '-created_at'], name='trader_auto_user_id_46f21d_idx'), models.Index(fields=['user', 'trading_environment', 'id'], name='trader_auto_user_id_8917de_idx')],
            },
        ),
    ]
