# Generated by Django 4.2.30 on 2026-04-19 01:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0009_automation_thought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksnapshot',
            name='captured_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quotesnapshot',
            name='captured_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
