# Generated by Django 4.2.30 on 2026-04-19 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0010_quotesnapshot_captured_at_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16)),
                ('as_of_ts_ms', models.BigIntegerField(db_index=True)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('regime', models.CharField(blank=True, db_index=True, max_length=32)),
                ('features', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_snapshots', to='trader.booksnapshot')),
                ('source_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_snapshots', to='trader.quotesnapshot')),
            ],
            options={
                'verbose_name': 'Snapshot de features',
                'verbose_name_plural': 'Snapshots de features',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticker', 'as_of_ts_ms'], name='trader_feat_ticker_7a442f_idx')],
            },
        ),
    ]
