# Generated by Django 4.2.30 on 2026-04-19 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trader', '0011_feature_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationMarketSimPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_environment', models.CharField(choices=[('simulator', 'Simulador'), ('real', 'Real')], db_index=True, max_length=16)),
                ('enabled', models.BooleanField(db_index=True, default=False)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('sim_ticker', models.CharField(blank=True, max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_market_sim_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferência de simulação de mercado (worker)',
                'verbose_name_plural': 'Preferências de simulação de mercado (worker)',
                'indexes': [models.Index(fields=['user', 'trading_environment', 'enabled'], name='trader_auto_user_id_ef9e70_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='automationmarketsimpreference',
            constraint=models.UniqueConstraint(fields=('user', 'trading_environment'), name='trader_automation_sim_pref_user_env_uniq'),
        ),
    ]
