# Generated by Django 4.2.30 on 2026-04-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0012_automation_market_sim_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationmarketsimpreference',
            name='replay_until',
            field=models.DateTimeField(blank=True, help_text='Instante máximo dos snapshots incluídos (scrubber de replay); vazio = dia completo.', null=True),
        ),
    ]
