# Generated by Django 4.2.30 on 2026-04-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0014_execution_profiles_and_markers'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='automationexecutionprofile',
            new_name='trader_auto_user_id_8e1b0a_idx',
            old_name='trader_auto_user_id_1adf0f_idx',
        ),
        migrations.RenameIndex(
            model_name='automationexecutionprofile',
            new_name='trader_auto_user_id_3e4df3_idx',
            old_name='trader_auto_user_id_416057_idx',
        ),
        migrations.RenameIndex(
            model_name='automationthought',
            new_name='trader_auto_executi_76246f_idx',
            old_name='trader_auto_executi_1a6015_idx',
        ),
        migrations.RenameIndex(
            model_name='automationtriggermarker',
            new_name='trader_auto_user_id_2ea741_idx',
            old_name='trader_auto_user_id_c64061_idx',
        ),
        migrations.RenameIndex(
            model_name='automationtriggermarker',
            new_name='trader_auto_executi_4314a1_idx',
            old_name='trader_auto_executi_d9456d_idx',
        ),
    ]
