# Generated by Django 4.2.30 on 2026-04-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0023_automationruntimepreference_max_daily_orders'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='automationruntimepreference',
            new_name='trader_auto_user_id_b02b8f_idx',
            old_name='trader_auto_user_id_476d2f_idx',
        ),
        migrations.RenameIndex(
            model_name='automationtrailingstoppreference',
            new_name='trader_auto_user_id_3810e2_idx',
            old_name='trader_auto__user_id_7a8b2c_idx',
        ),
        migrations.AlterField(
            model_name='automationexecutionprofile',
            name='trading_environment',
            field=models.CharField(choices=[('simulator', 'Simulador'), ('real', 'Real'), ('replay', 'Replay')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='automationmarketsimpreference',
            name='trading_environment',
            field=models.CharField(choices=[('simulator', 'Simulador'), ('real', 'Real'), ('replay', 'Replay')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='automationruntimepreference',
            name='trading_environment',
            field=models.CharField(choices=[('simulator', 'Simulador'), ('real', 'Real'), ('replay', 'Replay')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='automationstrategytoggle',
            name='trading_environment',
            field=models.CharField(choices=[('simulator', 'Simulador'), ('real', 'Real'), ('replay', 'Replay')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='automationthought',
            name='trading_environment',
            field=models.CharField(choices=[('simulator', 'Simulador'), ('real', 'Real'), ('replay', 'Replay')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='automationtrailingstoppreference',
            name='adjustment_enabled',
            field=models.BooleanField(default=True, help_text='Se falso, não se aplica trailing ao stop-limit após entrada (leafaR, tendência ativa, etc.).'),
        ),
        migrations.AlterField(
            model_name='automationtrailingstoppreference',
            name='trading_environment',
            field=models.CharField(choices=[('simulator', 'Simulador'), ('real', 'Real'), ('replay', 'Replay')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='automationtriggermarker',
            name='trading_environment',
            field=models.CharField(choices=[('simulator', 'Simulador'), ('real', 'Real'), ('replay', 'Replay')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='position',
            name='trading_environment',
            field=models.CharField(choices=[('simulator', 'Simulador'), ('real', 'Real'), ('replay', 'Replay')], db_index=True, default='simulator', max_length=16),
        ),
    ]
