"""
Django settings for ENTRADE project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from __future__ import annotations

import os
import re
import sys
from datetime import timedelta
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# utf-8-sig remove BOM no início do arquivo (comum no Bloco de Notas / Windows).
# override=True: se o shell tiver SMART_TRADER_* vazias, o .env ainda preenche.
load_dotenv(BASE_DIR / '.env', encoding='utf-8-sig', override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-etgj&nw=u+rnthg^$vvh2!+*d%ix%dq(0(^9-t2&3ybs_#98rs',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'false').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if h.strip()
]
# Com DEBUG=False, lista vazia faz o Django rejeitar todo Host (400). Sem isso /admin e o site quebram.
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '[::1]']

# Nome genérico na interface (evita expor o nome real do projeto na web).
PUBLIC_SITE_NAME = (os.environ.get('DJANGO_PUBLIC_SITE_NAME', 'Privado') or 'Privado').strip()

# Título no topo / home após login (painel autenticado).
SESSION_APP_TITLE = (os.environ.get('DJANGO_SESSION_APP_TITLE', 'Painel') or 'Painel').strip()


def _env_bool(name: str, default: bool = False) -> bool:
    v = os.environ.get(name, '')
    if v == '':
        return default
    return v.lower() in ('1', 'true', 'yes')


def _running_django_manage_test() -> bool:
    """Evita Redis obrigatório em ``manage.py test``."""
    try:
        return len(sys.argv) >= 2 and sys.argv[1] == 'test'
    except Exception:
        return False


def _build_caches() -> dict:
    """
    LocMem: um cache por processo Gunicorn.

    Redis (recomendado em produção): defina **só** ``DJANGO_CACHE_URL`` (ex. redis://127.0.0.1:6379/1).
    Não derivamos mais automaticamente do broker do Celery — URL errada bloqueava o site ao abrir
    qualquer página (timeout TCP no ``cache.get``). ``DJANGO_USE_REDIS_CACHE=1`` continua a
    permitir derivar de ``CELERY_BROKER_URL`` (DB lógico /1) se não houver ``DJANGO_CACHE_URL``.
    """
    loc: dict = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'entrade-api-auth',
        }
    }
    if _running_django_manage_test():
        return loc
    if 'pytest' in sys.modules:
        return loc
    if _env_bool('DJANGO_DISABLE_REDIS_CACHE', False):
        return loc
    url = (os.environ.get('DJANGO_CACHE_URL') or '').strip()
    if not url and _env_bool('DJANGO_USE_REDIS_CACHE', False):
        broker = (os.environ.get('CELERY_BROKER_URL') or '').strip()
        if broker.startswith(('redis://', 'rediss://')):
            if re.search(r'/\d+\s*$', broker):
                url = re.sub(r'/\d+\s*$', '/1', broker)
            else:
                url = broker.rstrip('/') + '/1'
    if not url:
        return loc
    try:
        sock = max(1, int(os.environ.get('DJANGO_REDIS_SOCKET_TIMEOUT_SEC', '3') or '3'))
    except ValueError:
        sock = 3
    return {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': url,
            'OPTIONS': {
                # redis.ConnectionPool (evita espera infinita se o host não responde).
                'socket_connect_timeout': sock,
                'socket_timeout': sock,
            },
        }
    }


def _postgres_options_from_url_query(query: str) -> dict:
    opts: dict = {}
    if not query:
        return opts
    for key, values in parse_qs(query, keep_blank_values=True).items():
        if not values:
            continue
        if key.lower() == 'sslmode' and values[0]:
            opts['sslmode'] = values[0]
    return opts


def _database_from_postgres_url(url: str) -> dict | None:
    """Aceita postgresql:// e postgres:// (Heroku / Docker)."""
    raw = (url or '').strip()
    if not raw:
        return None
    if raw.startswith('postgres://'):
        raw = 'postgresql://' + raw[len('postgres://') :]
    if not raw.startswith('postgresql://'):
        return None
    parsed = urlparse(raw)
    path = (parsed.path or '').lstrip('/')
    if not path:
        return None
    db: dict = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': unquote(path),
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or 'localhost',
        'PORT': str(parsed.port or 5432),
    }
    opts = _postgres_options_from_url_query(parsed.query or '')
    extra_ssl = (os.environ.get('DJANGO_DB_SSLMODE') or '').strip()
    if extra_ssl:
        opts['sslmode'] = extra_ssl
    if opts:
        db['OPTIONS'] = opts
    return db


def _database_from_postgres_env() -> dict | None:
    """PostgreSQL via variáveis DJANGO_DB_* (sem URL)."""
    name = (os.environ.get('DJANGO_DB_NAME') or '').strip()
    user = (os.environ.get('DJANGO_DB_USER') or '').strip()
    host = (os.environ.get('DJANGO_DB_HOST') or '').strip()
    if not (name and user and host):
        return None
    db: dict = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': name,
        'USER': user,
        'PASSWORD': os.environ.get('DJANGO_DB_PASSWORD', ''),
        'HOST': host,
        'PORT': (os.environ.get('DJANGO_DB_PORT') or '5432').strip() or '5432',
    }
    sslmode = (os.environ.get('DJANGO_DB_SSLMODE') or '').strip()
    if sslmode:
        db['OPTIONS'] = {'sslmode': sslmode}
    return db


def _conn_max_age() -> int:
    raw = (os.environ.get('DJANGO_DB_CONN_MAX_AGE') or '0').strip()
    try:
        return max(0, int(raw))
    except ValueError:
        return 0


def _sqlite_busy_timeout_sec() -> int:
    try:
        # Replay + perfil paralelo + Celery: espera longa no busy handler reduz OperationalError.
        return max(5, int(os.environ.get('DJANGO_SQLITE_BUSY_TIMEOUT_SEC', '90') or '90'))
    except ValueError:
        return 90


def _build_databases() -> dict:
    """
    PostgreSQL se DJANGO_DATABASE_URL / DATABASE_URL ou DJANGO_DB_NAME+USER+HOST.
    Caso contrário SQLite (db.sqlite3) para desenvolvimento sem Postgres.
    """
    for key in ('DJANGO_DATABASE_URL', 'DATABASE_URL'):
        cfg = _database_from_postgres_url(os.environ.get(key, ''))
        if cfg is not None:
            cfg['CONN_MAX_AGE'] = _conn_max_age()
            return {'default': cfg}
    cfg = _database_from_postgres_env()
    if cfg is not None:
        cfg['CONN_MAX_AGE'] = _conn_max_age()
        return {'default': cfg}
    return {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            # Segundos à espera de lock (vários workers + Celery = sem isto pode “congelar” o site).
            'OPTIONS': {'timeout': _sqlite_busy_timeout_sec()},
        }
    }


# HTTPS atrás do Nginx: cookies seguros e cabeçalho X-Forwarded-Proto.
# Defina DJANGO_BEHIND_HTTPS=1 no .env em produção (HTTPS).
if _env_bool('DJANGO_BEHIND_HTTPS', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = False  # redirecionamento SSL fica a cargo do Nginx
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '0') or '0')
    if SECURE_HSTS_SECONDS > 0:
        SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool(
            'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', False
        )

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'api_auth',
    'clearxp_websocket',
    'trader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'trader.middleware.TradingEnvironmentMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ENTRADE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'trader.context_processors.public_branding',
                'trader.context_processors.trading_environment',
                'trader.context_processors.collateral_custody_lists',
            ],
        },
    },
]

WSGI_APPLICATION = 'ENTRADE.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Postgres: driver psycopg 3 (pacote ``psycopg``). Configure URL ou DJANGO_DB_* no .env.

DATABASES = _build_databases()


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Admin e «hora local» do Django: BRT. Para UTC ou outro fuso: DJANGO_TIME_ZONE=UTC no ambiente.
TIME_ZONE = (os.environ.get('DJANGO_TIME_ZONE', '').strip() or 'America/Sao_Paulo')

USE_I18N = True

USE_TZ = True

# POST com muitos campos (admin: seleção em massa, changelist, etc.). Default Django = 1000.
# Ver ``TooManyFieldsSent`` / ``DATA_UPLOAD_MAX_NUMBER_FIELDS``.
DATA_UPLOAD_MAX_NUMBER_FIELDS = int(
    os.environ.get('DJANGO_DATA_UPLOAD_MAX_NUMBER_FIELDS', '50000') or '50000'
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_ROOT = BASE_DIR / 'media'

# Login do painel (templates em ``accounts``). Admin continua em ``/admin/login/``.
LOGIN_URL = '/entrar/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

CACHES = _build_caches()

# Redis (recomendado): DJANGO_CACHE_URL=redis://127.0.0.1:6379/1
# Ou DJANGO_USE_REDIS_CACHE=1 para derivar do CELERY_BROKER_URL (DB /1).

# Garantias/custódia: por defeito não bloquear o HTML (ver ``collateral_custody_context_for_template_request``).
# DJANGO_DEFER_COLLATERAL_SSR=0 — pré-carregar na SSR como antes.

# Lista intraday: DJANGO_ORDERS_INTRADAY_CACHE_SEC (default 10) — ver fetch_orders_cached em orders.py.

# Contratos desatualizados geram 404 na API e deixam o painel lento; ajuste ao rolar vencimento.
TRADER_WATCH_TICKERS = [
    t.strip().upper()
    for t in os.environ.get('TRADER_WATCH_TICKERS', 'WINJ26,WDOJ25').split(',')
    if t.strip()
]
# Opcional: após 404 em market data, segundos para não repetir GET ao mesmo ticker (ver marketdata.py).
# TRADER_MARKETDATA_404_CACHE_SEC=120
# TRADER_MARKETDATA_TIMEOUT_SEC=20

TRADER_WATCH_ENABLED = os.environ.get('TRADER_WATCH_ENABLED', 'false').lower() in ('1', 'true', 'yes')
# Beat agenda ``collect_watch_quotes`` a cada N segundos. Default 6s: com 2s várias execuções
# Celery em paralelo somavam CPU + estouravam limite global de quote (20 GET / 5s).
TRADER_WATCH_INTERVAL_SEC = max(1, int(os.environ.get('TRADER_WATCH_INTERVAL_SEC', '6')))
TRADER_WATCH_MAX_QUOTES_PER_RUN = max(
    1,
    int(
        os.environ.get(
            'TRADER_WATCH_MAX_QUOTES_PER_RUN',
            str(4 * TRADER_WATCH_INTERVAL_SEC),
        )
    ),
)
TRADER_WATCH_TASK_LOCK_SEC = max(
    3,
    int(
        os.environ.get(
            'TRADER_WATCH_TASK_LOCK_SEC',
            str(max(6, TRADER_WATCH_INTERVAL_SEC * 3)),
        )
    ),
)
TRADER_BOOK_WS_ENABLED = os.environ.get('TRADER_BOOK_WS_ENABLED', 'true').lower() in ('1', 'true', 'yes')
TRADER_BOOK_WS_TIMEOUT_SEC = float(os.environ.get('TRADER_BOOK_WS_TIMEOUT_SEC', '1.2') or '1.2')
TRADER_TICKER_NOT_ALLOWED_TTL_SEC = max(
    30,
    int(os.environ.get('TRADER_TICKER_NOT_ALLOWED_TTL_SEC', '600') or '600'),
)

# Quando a API indica pregão encerrado (status EndOfDay), o Celery entra em standby e não
# dispara quote/book até ``TRADER_WATCH_CLOSED_INTERVAL_SEC`` (próxima sonda).
TRADER_WATCH_STANDBY_ENABLED = _env_bool('TRADER_WATCH_STANDBY_ENABLED', True)
TRADER_WATCH_CLOSED_INTERVAL_SEC = max(
    60,
    int(os.environ.get('TRADER_WATCH_CLOSED_INTERVAL_SEC', '1800') or '1800'),
)

# Broker Redis (não passa pelo Nginx). Em produção: systemd ``celery-entrade-worker`` + ``celery-entrade-beat``.
# Lock/standby do Celery: mesmo host; DB lógico 0. O cache Django (token, marketdata, garantias)
# usa ``_build_caches()`` → Redis DB 1 quando ``CELERY_BROKER_URL`` é redis* (partilhado entre workers Gunicorn).
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULE = {
    'collect-watch-quote-snapshots': {
        'task': 'trader.tasks.collect_watch_quotes',
        'schedule': timedelta(seconds=TRADER_WATCH_INTERVAL_SEC),
    },
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '%(asctime)s %(levelname)s %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        # Logs de diagnóstico da abertura de ambiente manual/automações.
        'trader.views': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_TRADER_VIEWS_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'trader.panel_context': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_TRADER_PANEL_CONTEXT_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.environ.get('DJANGO_ROOT_LOG_LEVEL', 'WARNING'),
    },
}
